[project]
name = "my-blog-backend"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.128.0",
    "gunicorn>=24.0.0",
    "pydantic-settings>=2.12.0",
    "pytest>=9.0.2",
    "uvicorn>=0.40.0",
]
